import 'package:flutter/material.dart';

// Função para obter o ícone correspondente à string da API
IconData getMdiIconToFlutterIcon(String mdiIcon) {
  return iconMapping[mdiIcon] ??
      Icons.nearby_error; // Ícone de erro padrão se não houver correspondência
}

final Map<String, IconData> iconMapping = {
  'mdiClose': Icons.close,
  'mdiChartTimelineVariantShimmer': Icons.timeline,
  'mdiChartTimelineVariant': Icons.timeline,
  'mdiChartDonut': Icons.donut_large,
  'mdiChartPie': Icons.pie_chart,
  'mdiChartBar': Icons.bar_chart,
  'mdiChartWaterfall': Icons.waterfall_chart,
  'mdiChartBox': Icons.insert_chart_outlined,
  'mdiBank': Icons.account_balance,
  'mdiGavel': Icons.gavel,
  'mdiCart': Icons.shopping_cart,
  'mdiCurrencyUsd': Icons.attach_money,
  'mdiCreditCardOutline': Icons.credit_card_outlined,
  'mdiBasket': Icons.shopping_basket,
  'mdiSwapHorizontalCircle': Icons.swap_horizontal_circle,
  'mdiWallet': Icons.account_balance_wallet,
  'mdiBriefcase': Icons.work,
  'mdiInboxMultiple': Icons.all_inbox,
  'mdiShopping': Icons.shopping_bag,
  'mdiBookOpen': Icons.menu_book_rounded,
  'mdiClipboardText': Icons.paste,
  'mdiClipboardTextClockOutline': Icons.access_time,
  'mdiFileDocument': Icons.description,
  'mdiTextBox': Icons.text_snippet_rounded,
  'mdiTextBoxCheck': Icons.text_snippet_rounded,
  'mdiFileAccount': Icons.switch_account,
  'mdiPlaylistCheck': Icons.playlist_add_check,
  'mdiRadar': Icons.radar,
  'mdiBookmarkMultiple': Icons.bookmarks_rounded,
  'mdiLabel': Icons.label,
  'mdiCalendarAccount': Icons.perm_contact_calendar_outlined,
  'mdiClipboardAccount': Icons.perm_contact_cal,
  'mdiForum': Icons.forum,
  'mdiFingerprint': Icons.fingerprint,
  'mdiAccountCircle': Icons.account_circle,
  'mdiAccountMultiple': Icons.people,
  'mdiAccountVoice': Icons.record_voice_over,
  'mdiWrench': Icons.build,
  'mdiCog': Icons.settings,
  'mdiDns': Icons.dns,
  'mdiThumbUp': Icons.thumb_up,
  'mdiThumbDown': Icons.thumb_down,
  'mdiThumbsUpDown': Icons.thumbs_up_down,
  'mdiWeb': Icons.web,
  'mdiLeaf': Icons.eco,
  'mdiCheckDecagram': Icons.verified,
  'mdiShieldCheck': Icons.verified_user,
  'mdiCheckCircle': Icons.check_circle,
  'mdiShieldAccount': Icons.verified_user,
  'mdiCalendarBlank': Icons.calendar_today,
  'mdiCalendarToday': Icons.today,
  'mdiCalendar': Icons.today,
  'mdiCalendarRange': Icons.date_range,
  'mdiBackupRestore': Icons.restore,
  'mdiTableMultiple': Icons.backup_table_rounded,
  'mdiFormatListBulleted': Icons.format_list_bulleted,
  'mdiBillboard': Icons.dashboard,
  'mdiAccountCheck': Icons.person_add_alt_1,
  'mdiAccountMultipleRemoveOutline': Icons.group_remove_outlined,
  'mdiAccountSupervisorCircle': Icons.supervised_user_circle,
  'mdiAccountCardOutline': Icons.credit_card_outlined,
  'mdiAccountTieWoman': Icons.assignment_ind,
  'mdiAccountTie': Icons.assignment_ind,
  'mdiAccount': Icons.account_box,
  'mdiStackExchange': Icons.swap_vert,
  'mdiFoodDrumstickOffOutline': Icons.no_food,
  'mdiFoodDrumstickOff': Icons.no_food,
  'mdiFoodDrumstick': Icons.fastfood,
  'mdiFood': Icons.fastfood,
  'mdiDoorOpen': Icons.door_back_door,
  'mdiDomain': Icons.domain,
  'mdiContentPaste': Icons.content_paste,
  'mdiSitemap': Icons.web,
  'mdiAccountMultipleOutline': Icons.people_outline,
  'mdiLightbulbOnOutline': Icons.lightbulb_outline,
  'mdiFinance': Icons.account_balance,
  'mdiChartBoxOutline': Icons.insert_chart_outlined,
  'mdiCashClock': Icons.access_time,
  'mdiCalculatorVariantOutline': Icons.calculate_outlined,
  'mdiCellphone': Icons.smartphone_rounded
};
