name: open_mitra_mobile
description: "Mitra"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  firebase_core: ^3.5.0
  device_info_plus: ^9.1.1
  flutter_svg: ^2.0.9
  hexcolor: ^3.0.1
  webview_flutter: ^4.10.0
  file_picker: ^7.0.2
  path_provider: ^2.1.4
  flutter_holo_date_picker: ^1.1.0
  intl: ^0.19.0
  youtube_player_flutter: ^9.0.4
  package_info_plus: ^8.0.2
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.0
  animated_text_kit: ^4.2.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  launcher_name: ^1.0.2

flutter:
  assets:
    - assets/images/
    - assets/svg/
    - assets/icon/
    - assets/index.html
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/NanumMyeongjo-Bold.ttf
          weight: 700
        - asset: assets/fonts/NanumMyeongjo-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/NanumMyeongjo-Regular.ttf
    - family: Prata
      fonts:
        - asset: assets/fonts/Prata-Regular.ttf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icone-teste.jpg"
  remove_alpha_ios: true

launcher_name:
  default: "Mitra Open"
