String appName = 'Mitra Open';
String appLocalAppImageIconPath = 'assets/icon/icone-teste.jpg';
String appDomain = 'mitraecp.com';
int appWorkspaceId = 0;
int appProjectId = 0;
String appProjectLogoUrl = '';
String appProjectLocalLogoPath = 'assets/icon/icone-teste.jpg';
String appProjectName = '';
String appProjectPrimaryColor = '';